source 'https://rubygems.org'

gem 'bourbon'
gem 'coffee-script'
gem 'github-pages'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-assets-autoprefixer'
gem 'jekyll-haml'
gem 'jekyll-feed'
gem 'neat'
gem 'sass'
gem 'uglifier'